#Step 0
DROP DATABASE IF EXISTS hospital_staging;
CREATE DATABASE hospital_staging;
USE hospital_staging;

#Step 1: Create Staging Tables (raw data to process all csv files)
-- haven't set constraints yet
DROP TABLE IF EXISTS stg_patients;
CREATE TABLE IF NOT EXISTS stg_patients (
  Id VARCHAR(64), BIRTHDATE DATE, DEATHDATE DATE, SSN VARCHAR(32), DRIVERS VARCHAR(64),
  PASSPORT VARCHAR(64), PREFIX VARCHAR(16), FIRST VARCHAR(64), LAST VARCHAR(64), SUFFIX VARCHAR(16),
  MAIDEN VARCHAR(64), MARITAL VARCHAR(32), RACE VARCHAR(64), ETHNICITY VARCHAR(64), GENDER VARCHAR(16),
  BIRTHPLACE VARCHAR(128), ADDRESS VARCHAR(128), CITY VARCHAR(64), STATE VARCHAR(32), COUNTY VARCHAR(64),
  ZIP VARCHAR(16), LAT DECIMAL(9,6), LON DECIMAL(9,6),
  HEALTHCARE_EXPENSES DECIMAL(14,2), HEALTHCARE_COVERAGE DECIMAL(14,2)
);

DROP TABLE IF EXISTS stg_organizations;
CREATE TABLE IF NOT EXISTS stg_organizations (
  Id VARCHAR(64), NAME VARCHAR(255), ADDRESS VARCHAR(128), CITY VARCHAR(64), STATE VARCHAR(32), ZIP VARCHAR(16),
  LAT DECIMAL(9,6), LON DECIMAL(9,6), PHONE VARCHAR(32), REVENUE DECIMAL(16,2), UTILIZATION DECIMAL(9,2)
);

DROP TABLE IF EXISTS stg_providers; 
CREATE TABLE IF NOT EXISTS stg_providers (
  Id VARCHAR(64), ORGANIZATION VARCHAR(64), NAME VARCHAR(255), GENDER VARCHAR(16), SPECIALITY VARCHAR(128),
  ADDRESS VARCHAR(128), CITY VARCHAR(64), STATE VARCHAR(32), ZIP VARCHAR(16),
  LAT DECIMAL(9,6), LON DECIMAL(9,6), UTILIZATION DECIMAL(6,2)
);

DROP TABLE IF EXISTS stg_encounters; 
CREATE TABLE IF NOT EXISTS stg_encounters (
  Id VARCHAR(64), START DATETIME, STOP DATETIME, PATIENT VARCHAR(64), ORGANIZATION VARCHAR(64), PROVIDER VARCHAR(64),
  PAYER VARCHAR(64), ENCOUNTERCLASS VARCHAR(64), CODE VARCHAR(64), DESCRIPTION VARCHAR(255),
  BASE_ENCOUNTER_COST DECIMAL(14,2), TOTAL_CLAIM_COST DECIMAL(14,2), PAYER_COVERAGE DECIMAL(14,2),
  REASONCODE VARCHAR(64), REASONDESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS stg_conditions; 
CREATE TABLE IF NOT EXISTS stg_conditions (
  START DATETIME, STOP DATETIME, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64), CODE VARCHAR(64), DESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS stg_careplans; 
CREATE TABLE IF NOT EXISTS stg_careplans (
  Id VARCHAR(64), START DATETIME, STOP DATETIME, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64),
  CODE VARCHAR(64), DESCRIPTION VARCHAR(255), REASONCODE VARCHAR(64), REASONDESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS stg_devices; 
CREATE TABLE IF NOT EXISTS stg_devices (
  START DATETIME, STOP DATETIME, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64),
  CODE VARCHAR(64), DESCRIPTION VARCHAR(255), UDI VARCHAR(128)
);

DROP TABLE IF EXISTS stg_imaging_studies; 
CREATE TABLE IF NOT EXISTS stg_imaging_studies (
  Id VARCHAR(64), DATE DATETIME, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64),
  BODYSITE_CODE VARCHAR(64), BODYSITE_DESCRIPTION VARCHAR(255),
  MODALITY_CODE VARCHAR(32), MODALITY_DESCRIPTION VARCHAR(128),
  SOP_CODE VARCHAR(32), SOP_DESCRIPTION VARCHAR(128)
);

DROP TABLE IF EXISTS stg_immunizations; 
CREATE TABLE IF NOT EXISTS stg_immunizations (
  DATE DATETIME, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64), CODE VARCHAR(64),
  DESCRIPTION VARCHAR(255), BASE_COST DECIMAL(14,2)
);

DROP TABLE IF EXISTS stg_medications; 
CREATE TABLE IF NOT EXISTS stg_medications (
  START DATETIME, STOP DATETIME, PATIENT VARCHAR(64), PAYER VARCHAR(64), ENCOUNTER VARCHAR(64),
  CODE VARCHAR(64), DESCRIPTION VARCHAR(255), BASE_COST DECIMAL(14,2), PAYER_COVERAGE DECIMAL(14,2),
  DISPENSES INT, TOTALCOST DECIMAL(14,2), REASONCODE VARCHAR(64), REASONDESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS stg_observations; 
CREATE TABLE IF NOT EXISTS stg_observations (
  DATE DATETIME, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64), CODE VARCHAR(64), DESCRIPTION VARCHAR(255),
  VALUE VARCHAR(128), UNITS VARCHAR(32), TYPE VARCHAR(32)
);

DROP TABLE IF EXISTS stg_allergies; 
CREATE TABLE IF NOT EXISTS stg_allergies (
  START DATE, STOP DATE, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64), CODE VARCHAR(64), DESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS stg_procedures; 
CREATE TABLE IF NOT EXISTS stg_procedures (
  DATE DATETIME, PATIENT VARCHAR(64), ENCOUNTER VARCHAR(64), CODE VARCHAR(64),
  DESCRIPTION VARCHAR(255), BASE_COST DECIMAL(14,2), REASONCODE VARCHAR(64), REASONDESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS stg_payers; 
CREATE TABLE IF NOT EXISTS stg_payers (
  Id VARCHAR(64), NAME VARCHAR(255), ADDRESS VARCHAR(128), CITY VARCHAR(64), STATE_HEADQUARTERED VARCHAR(32),
  ZIP VARCHAR(16), PHONE VARCHAR(32),
  AMOUNT_COVERED DECIMAL(16,2), AMOUNT_UNCOVERED DECIMAL(16,2), REVENUE DECIMAL(16,2),
  COVERED_ENCOUNTERS BIGINT, UNCOVERED_ENCOUNTERS BIGINT, COVERED_MEDICATIONS BIGINT, UNCOVERED_MEDICATIONS BIGINT,
  COVERED_PROCEDURES BIGINT, UNCOVERED_PROCEDURES BIGINT, COVERED_IMMUNIZATIONS BIGINT, UNCOVERED_IMMUNIZATIONS BIGINT,
  UNIQUE_CUSTOMERS BIGINT, QOLS_AVG DECIMAL(6,3), MEMBER_MONTHS BIGINT
);

DROP TABLE IF EXISTS stg_payer_transitions; 
CREATE TABLE IF NOT EXISTS stg_payer_transitions (
  PATIENT VARCHAR(64), START_YEAR INT, END_YEAR INT, PAYER VARCHAR(64), OWNERSHIP VARCHAR(64)
);

#Load CSV files from disk and populate the tables
-- Enable LOCAL INFILE in client/server settings
SHOW GLOBAL VARIABLES LIKE 'local_infile';   -- should become ON (1)
SET GLOBAL local_infile = 1;
SET PERSIST local_infile = 1;
 
-- Patients
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/patients.csv'
INTO TABLE stg_patients
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id,@BIRTHDATE,@DEATHDATE,@SSN,@DRIVERS,@PASSPORT,@PREFIX,@FIRST,@LAST,@SUFFIX,
 @MAIDEN,@MARITAL,@RACE,@ETHNICITY,@GENDER,@BIRTHPLACE,@ADDRESS,@CITY,@STATE,@COUNTY,
 @ZIP,@LAT,@LON,@HEALTHCARE_EXPENSES,@HEALTHCARE_COVERAGE)
SET
  Id        = NULLIF(@Id,''),
  BIRTHDATE = NULLIF(@BIRTHDATE,''),
  DEATHDATE = NULLIF(@DEATHDATE,''),             
  SSN       = NULLIF(@SSN,''),
  DRIVERS   = NULLIF(@DRIVERS,''),
  PASSPORT  = NULLIF(@PASSPORT,''),
  PREFIX    = NULLIF(@PREFIX,''),
  -- remove any digits at the end of the name
  FIRST     = NULLIF(REGEXP_REPLACE(@FIRST,  '[0-9]+$', ''),''),
  LAST      = NULLIF(REGEXP_REPLACE(@LAST,   '[0-9]+$', ''),''),
  SUFFIX    = NULLIF(@SUFFIX,''),
  MAIDEN    = NULLIF(REGEXP_REPLACE(@MAIDEN, '[0-9]+$', ''),''),
  MARITAL   = NULLIF(@MARITAL,''),
  RACE      = NULLIF(@RACE,''),
  ETHNICITY = NULLIF(@ETHNICITY,''),
  GENDER    = NULLIF(@GENDER,''),
  BIRTHPLACE= NULLIF(@BIRTHPLACE,''),
  ADDRESS   = NULLIF(@ADDRESS,''),
  CITY      = NULLIF(@CITY,''),
  STATE     = NULLIF(@STATE,''),
  COUNTY    = NULLIF(@COUNTY,''),
  ZIP       = NULLIF(@ZIP,''),
  LAT       = CAST(NULLIF(@LAT,'') AS DECIMAL(9,6)),  
  LON       = CAST(NULLIF(@LON,'') AS DECIMAL(9,6)),
  HEALTHCARE_EXPENSES = CAST(NULLIF(@HEALTHCARE_EXPENSES,'') AS DECIMAL(14,2)),
  HEALTHCARE_COVERAGE = CAST(NULLIF(@HEALTHCARE_COVERAGE,'') AS DECIMAL(14,2));


-- Helper Function
DROP FUNCTION IF EXISTS fn_proper_case;
DELIMITER $$

CREATE FUNCTION fn_proper_case(p_input VARCHAR(255))
RETURNS VARCHAR(255)
DETERMINISTIC
BEGIN
  DECLARE len  INT;
  DECLARE pos  INT DEFAULT 1;
  DECLARE word VARCHAR(255);
  DECLARE res  VARCHAR(255) DEFAULT '';

  IF p_input IS NULL OR p_input = '' THEN
    RETURN NULL;
  END IF;

  SET len = CHAR_LENGTH(p_input);

  main_loop: WHILE pos <= len DO
    -- 1) copy all spaces exactly
    WHILE pos <= len AND SUBSTRING(p_input, pos, 1) = ' ' DO
      SET res = CONCAT(res, ' ');
      SET pos = pos + 1;
    END WHILE;

    IF pos > len THEN
      LEAVE main_loop;
    END IF;

    -- 2) collect one word (non-space chars)
    SET word = '';
    WHILE pos <= len AND SUBSTRING(p_input, pos, 1) <> ' ' DO
      SET word = CONCAT(word, SUBSTRING(p_input, pos, 1));
      SET pos  = pos + 1;
    END WHILE;

    -- 3) Title-case the word: first letter upper, rest lower
    SET word = CONCAT(
                 UPPER(LEFT(word, 1)),
                 LOWER(SUBSTRING(word, 2))
               );

    -- 4) append to result
    SET res = CONCAT(res, word);
  END WHILE;

  RETURN res;
END$$

DELIMITER ;


-- Organizations
TRUNCATE TABLE stg_organizations;

LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/organizations.csv'
INTO TABLE stg_organizations
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id,@NAME,@ADDRESS,@CITY,@STATE,@ZIP,@LAT,@LON,@PHONE,@REVENUE,@UTILIZATION)
SET
  Id = NULLIF(@Id,''),
  -- NAME: keep PCP codes as-is, otherwise proper case
  NAME = CASE
           WHEN @NAME IS NULL OR @NAME = '' THEN NULL
           WHEN @NAME REGEXP '^PCP[0-9]+' THEN @NAME
           ELSE fn_proper_case(@NAME)
         END,
  ADDRESS = CASE
              WHEN @ADDRESS IS NULL OR @ADDRESS = '' THEN NULL
              ELSE fn_proper_case(@ADDRESS)
            END,
  CITY = CASE
           WHEN @CITY IS NULL OR @CITY = '' THEN NULL
           ELSE fn_proper_case(@CITY)
         END,
  STATE = NULLIF(@STATE,''),
  ZIP   = NULLIF(@ZIP,''),
  LAT = CAST(NULLIF(@LAT,'') AS DECIMAL(9,6)),
  LON = CAST(NULLIF(@LON,'') AS DECIMAL(9,6)),
  PHONE =
    CASE
      WHEN @PHONE = '' THEN NULL
      ELSE
        CASE
          WHEN LENGTH(REGEXP_REPLACE(@PHONE, '[^0-9]', '')) = 10 THEN
            CONCAT(
              SUBSTRING(REGEXP_REPLACE(@PHONE, '[^0-9]', ''),1,3), '-',
              SUBSTRING(REGEXP_REPLACE(@PHONE, '[^0-9]', ''),4,3), '-',
              SUBSTRING(REGEXP_REPLACE(@PHONE, '[^0-9]', ''),7,4)
            )
          ELSE REGEXP_REPLACE(@PHONE, '[^0-9]', '')
        END
    END,
  REVENUE     = CAST(NULLIF(@REVENUE,'') AS DECIMAL(16,2)),
  UTILIZATION = CAST(NULLIF(@UTILIZATION,'') AS DECIMAL(6,2));

-- Providers
TRUNCATE TABLE stg_providers;

LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/providers.csv'
INTO TABLE stg_providers
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id,@ORGANIZATION,@NAME,@GENDER,@SPECIALITY,@ADDRESS,@CITY,@STATE,@ZIP,@LAT,@LON,@UTILIZATION)
SET
  Id           = NULLIF(@Id,''),
  ORGANIZATION = NULLIF(@ORGANIZATION,''),

  -- NAME: remove digits, replace underscores with spaces, then proper case
  NAME = CASE
           WHEN @NAME IS NULL OR @NAME = '' THEN NULL
           ELSE fn_proper_case(
                  REPLACE(
                    REGEXP_REPLACE(@NAME, '[0-9]+', ''),   -- drop all digits
                    '_', ' '                               -- turn _ into space
                  )
                )
         END,

  GENDER = NULLIF(@GENDER,''),

  SPECIALITY = CASE
                 WHEN @SPECIALITY IS NULL OR @SPECIALITY = '' THEN NULL
                 ELSE fn_proper_case(REPLACE(@SPECIALITY, '_', ' '))
               END,

  ADDRESS = CASE
              WHEN @ADDRESS IS NULL OR @ADDRESS = '' THEN NULL
              ELSE fn_proper_case(REPLACE(@ADDRESS, '_', ' '))
            END,

  CITY = CASE
           WHEN @CITY IS NULL OR @CITY = '' THEN NULL
           ELSE fn_proper_case(REPLACE(@CITY, '_', ' '))
         END,

  STATE = NULLIF(@STATE,''),
  ZIP   = NULLIF(@ZIP,''),

  LAT         = CAST(NULLIF(@LAT,'') AS DECIMAL(9,6)),
  LON         = CAST(NULLIF(@LON,'') AS DECIMAL(9,6)),
  UTILIZATION = CAST(NULLIF(@UTILIZATION,'') AS DECIMAL(6,2));


-- Encounters
TRUNCATE TABLE stg_encounters;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/encounters.csv'
INTO TABLE stg_encounters
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id,@START,@STOP,@PATIENT,@ORGANIZATION,@PROVIDER,@PAYER,@ENCOUNTERCLASS,@CODE,@DESCRIPTION,
 @BASE_ENCOUNTER_COST,@TOTAL_CLAIM_COST,@PAYER_COVERAGE,@REASONCODE,@REASONDESCRIPTION)
SET
  Id   = NULLIF(@Id,''),
  START = CASE WHEN @START='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@START,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  STOP  = CASE WHEN @STOP ='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@STOP ,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  PATIENT        = NULLIF(@PATIENT,''),
  ORGANIZATION   = NULLIF(@ORGANIZATION,''),
  PROVIDER       = NULLIF(@PROVIDER,''),
  PAYER          = NULLIF(@PAYER,''),
  ENCOUNTERCLASS = NULLIF(@ENCOUNTERCLASS,''),
  CODE           = NULLIF(@CODE,''),
  DESCRIPTION    = NULLIF(@DESCRIPTION,''),
  BASE_ENCOUNTER_COST = CAST(NULLIF(@BASE_ENCOUNTER_COST,'') AS DECIMAL(14,2)),
  TOTAL_CLAIM_COST    = CAST(NULLIF(@TOTAL_CLAIM_COST,'')    AS DECIMAL(14,2)),
  PAYER_COVERAGE      = CAST(NULLIF(@PAYER_COVERAGE,'')      AS DECIMAL(14,2)),
  REASONCODE          = NULLIF(@REASONCODE,''),
  REASONDESCRIPTION   = NULLIF(@REASONDESCRIPTION,'');


-- Conditions
TRUNCATE TABLE stg_conditions;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/conditions.csv'
INTO TABLE stg_conditions
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@START,@STOP,@PATIENT,@ENCOUNTER,@CODE,@DESCRIPTION)
SET
  START = CASE WHEN @START='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@START,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  STOP  = CASE WHEN @STOP ='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@STOP ,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  PATIENT     = NULLIF(@PATIENT,''),
  ENCOUNTER   = NULLIF(@ENCOUNTER,''),
  CODE        = NULLIF(@CODE,''),
  DESCRIPTION = NULLIF(@DESCRIPTION,'');

-- Careplans
TRUNCATE TABLE stg_careplans;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/careplans.csv'
INTO TABLE stg_careplans
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id,@START,@STOP,@PATIENT,@ENCOUNTER,@CODE,@DESCRIPTION,@REASONCODE,@REASONDESCRIPTION)
SET
  Id   = NULLIF(@Id,''),
  START = CASE WHEN @START='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@START,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  STOP  = CASE WHEN @STOP ='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@STOP ,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  PATIENT          = NULLIF(@PATIENT,''),
  ENCOUNTER        = NULLIF(@ENCOUNTER,''),
  CODE             = NULLIF(@CODE,''),
  DESCRIPTION      = NULLIF(@DESCRIPTION,''),
  REASONCODE       = NULLIF(@REASONCODE,''),
  REASONDESCRIPTION= NULLIF(@REASONDESCRIPTION,'');

-- Devices
TRUNCATE TABLE stg_devices;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/devices.csv'
INTO TABLE stg_devices
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@START,@STOP,@PATIENT,@ENCOUNTER,@CODE,@DESCRIPTION,@UDI)
SET
  START = CASE WHEN @START='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@START,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  STOP  = CASE WHEN @STOP ='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@STOP ,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  PATIENT     = NULLIF(@PATIENT,''),
  ENCOUNTER   = NULLIF(@ENCOUNTER,''),
  CODE        = NULLIF(@CODE,''),
  DESCRIPTION = NULLIF(@DESCRIPTION,''),
  UDI         = NULLIF(@UDI,'');

-- Imaging_studies
TRUNCATE TABLE stg_imaging_studies;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/imaging_studies.csv'
INTO TABLE stg_imaging_studies
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id,@DATE,@PATIENT,@ENCOUNTER,@BODYSITE_CODE,@BODYSITE_DESCRIPTION,
 @MODALITY_CODE,@MODALITY_DESCRIPTION,@SOP_CODE,@SOP_DESCRIPTION)
SET
  Id   = NULLIF(@Id,''),
  DATE = CASE WHEN @DATE='' THEN NULL
              ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@DATE,'.',1),'T',' '),'Z',''),
                               '%Y-%m-%d %H:%i:%s') END,
  PATIENT              = NULLIF(@PATIENT,''),
  ENCOUNTER            = NULLIF(@ENCOUNTER,''),
  BODYSITE_CODE        = NULLIF(@BODYSITE_CODE,''),
  BODYSITE_DESCRIPTION = NULLIF(@BODYSITE_DESCRIPTION,''),
  MODALITY_CODE        = NULLIF(@MODALITY_CODE,''),
  MODALITY_DESCRIPTION = NULLIF(@MODALITY_DESCRIPTION,''),
  SOP_CODE             = NULLIF(@SOP_CODE,''),
  SOP_DESCRIPTION      = NULLIF(@SOP_DESCRIPTION,'');

-- Immunizations
TRUNCATE TABLE stg_immunizations;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/immunizations.csv'
INTO TABLE stg_immunizations
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATE,@PATIENT,@ENCOUNTER,@CODE,@DESCRIPTION,@BASE_COST)
SET
  DATE = CASE WHEN @DATE='' THEN NULL
              ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@DATE,'.',1),'T',' '),'Z',''),
                               '%Y-%m-%d %H:%i:%s') END,
  PATIENT     = NULLIF(@PATIENT,''),
  ENCOUNTER   = NULLIF(@ENCOUNTER,''),
  CODE        = NULLIF(@CODE,''),
  DESCRIPTION = NULLIF(@DESCRIPTION,''),
  BASE_COST   = CAST(NULLIF(@BASE_COST,'') AS DECIMAL(14,2));

-- Medications
TRUNCATE TABLE stg_medications;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/medications.csv'
INTO TABLE stg_medications
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@START,@STOP,@PATIENT,@PAYER,@ENCOUNTER,@CODE,@DESCRIPTION,@BASE_COST,@PAYER_COVERAGE,
 @DISPENSES,@TOTALCOST,@REASONCODE,@REASONDESCRIPTION)
SET
  START = CASE WHEN @START='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@START,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  STOP  = CASE WHEN @STOP ='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@STOP ,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  PATIENT          = NULLIF(@PATIENT,''),
  PAYER            = NULLIF(@PAYER,''),
  ENCOUNTER        = NULLIF(@ENCOUNTER,''),
  CODE             = NULLIF(@CODE,''),
  DESCRIPTION      = NULLIF(@DESCRIPTION,''),
  BASE_COST        = CAST(NULLIF(@BASE_COST,'') AS DECIMAL(14,2)),
  PAYER_COVERAGE   = CAST(NULLIF(@PAYER_COVERAGE,'') AS DECIMAL(14,2)),
  DISPENSES        = CAST(NULLIF(@DISPENSES,'') AS SIGNED),
  TOTALCOST        = CAST(NULLIF(@TOTALCOST,'') AS DECIMAL(14,2)),
  REASONCODE       = NULLIF(@REASONCODE,''),
  REASONDESCRIPTION= NULLIF(@REASONDESCRIPTION,'');

-- Obervations
TRUNCATE TABLE stg_observations;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/observations.csv'
INTO TABLE stg_observations
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATE,@PATIENT,@ENCOUNTER,@CODE,@DESCRIPTION,@VALUE,@UNITS,@TYPE)
SET
  DATE = CASE WHEN @DATE='' THEN NULL
              ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@DATE,'.',1),'T',' '),'Z',''),
                               '%Y-%m-%d %H:%i:%s') END,
  PATIENT     = NULLIF(@PATIENT,''),
  ENCOUNTER   = NULLIF(@ENCOUNTER,''),
  CODE        = NULLIF(@CODE,''),
  DESCRIPTION = NULLIF(@DESCRIPTION,''),
  VALUE       = NULLIF(@VALUE,''),
  UNITS       = NULLIF(@UNITS,''),
  TYPE        = NULLIF(@TYPE,'');

-- Allergies
TRUNCATE TABLE stg_allergies;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/allergies.csv'
INTO TABLE stg_allergies
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@START,@STOP,@PATIENT,@ENCOUNTER,@CODE,@DESCRIPTION)
SET
  START = CASE WHEN @START='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@START,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  STOP  = CASE WHEN @STOP ='' THEN NULL
               ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@STOP ,'.',1),'T',' '),'Z',''),
                                '%Y-%m-%d %H:%i:%s') END,
  PATIENT     = NULLIF(@PATIENT,''),
  ENCOUNTER   = NULLIF(@ENCOUNTER,''),
  CODE        = NULLIF(@CODE,''),
  DESCRIPTION = NULLIF(@DESCRIPTION,'');

-- Procedures
TRUNCATE TABLE stg_procedures;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/procedures.csv'
INTO TABLE stg_procedures
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATE,@PATIENT,@ENCOUNTER,@CODE,@DESCRIPTION,@BASE_COST,@REASONCODE,@REASONDESCRIPTION)
SET
  DATE = CASE WHEN @DATE='' THEN NULL
              ELSE STR_TO_DATE(REPLACE(REPLACE(SUBSTRING_INDEX(@DATE,'.',1),'T',' '),'Z',''),
                               '%Y-%m-%d %H:%i:%s') END,
  PATIENT          = NULLIF(@PATIENT,''),
  ENCOUNTER        = NULLIF(@ENCOUNTER,''),
  CODE             = NULLIF(@CODE,''),
  DESCRIPTION      = NULLIF(@DESCRIPTION,''),
  BASE_COST        = CAST(NULLIF(@BASE_COST,'') AS DECIMAL(14,2)),
  REASONCODE       = NULLIF(@REASONCODE,''),
  REASONDESCRIPTION= NULLIF(@REASONDESCRIPTION,'');

-- Payers
TRUNCATE TABLE stg_payers;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/payers.csv'
INTO TABLE stg_payers
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id,@NAME,@ADDRESS,@CITY,@STATE_HEADQUARTERED,@ZIP,@PHONE,
 @AMOUNT_COVERED,@AMOUNT_UNCOVERED,@REVENUE,
 @COVERED_ENCOUNTERS,@UNCOVERED_ENCOUNTERS,@COVERED_MEDICATIONS,@UNCOVERED_MEDICATIONS,
 @COVERED_PROCEDURES,@UNCOVERED_PROCEDURES,@COVERED_IMMUNIZATIONS,@UNCOVERED_IMMUNIZATIONS,
 @UNIQUE_CUSTOMERS,@QOLS_AVG,@MEMBER_MONTHS)
SET
  Id                   = NULLIF(@Id,''),
  NAME = CASE
           WHEN UPPER(@NAME) = 'NO_INSURANCE' THEN 'No Insurance'
           WHEN @NAME = 'UnitedHealthcare'     THEN 'United Healthcare'
           ELSE fn_proper_case(REPLACE(NULLIF(@NAME,''), '_', ' '))
         END,
  ADDRESS              = NULLIF(@ADDRESS,''),
  CITY                 = NULLIF(@CITY,''),
  STATE_HEADQUARTERED  = NULLIF(@STATE_HEADQUARTERED,''),
  ZIP                  = NULLIF(@ZIP,''),
  PHONE                = NULLIF(@PHONE,''),
  AMOUNT_COVERED       = CAST(NULLIF(@AMOUNT_COVERED,'')    AS DECIMAL(16,2)),
  AMOUNT_UNCOVERED     = CAST(NULLIF(@AMOUNT_UNCOVERED,'')  AS DECIMAL(16,2)),
  REVENUE              = CAST(NULLIF(@REVENUE,'')           AS DECIMAL(16,2)),
  COVERED_ENCOUNTERS     = NULLIF(@COVERED_ENCOUNTERS,''),
  UNCOVERED_ENCOUNTERS   = NULLIF(@UNCOVERED_ENCOUNTERS,''),
  COVERED_MEDICATIONS    = NULLIF(@COVERED_MEDICATIONS,''),
  UNCOVERED_MEDICATIONS  = NULLIF(@UNCOVERED_MEDICATIONS,''),
  COVERED_PROCEDURES     = NULLIF(@COVERED_PROCEDURES,''),
  UNCOVERED_PROCEDURES   = NULLIF(@UNCOVERED_PROCEDURES,''),
  COVERED_IMMUNIZATIONS  = NULLIF(@COVERED_IMMUNIZATIONS,''),
  UNCOVERED_IMMUNIZATIONS= NULLIF(@UNCOVERED_IMMUNIZATIONS,''),
  UNIQUE_CUSTOMERS      = NULLIF(@UNIQUE_CUSTOMERS,''),
  QOLS_AVG              = CAST(NULLIF(@QOLS_AVG,'')         AS DECIMAL(6,3)),
  MEMBER_MONTHS         = NULLIF(@MEMBER_MONTHS,'');

-- Payer_transitions
TRUNCATE TABLE stg_payer_transitions;
LOAD DATA LOCAL INFILE '/Users/apple/Desktop/603_csv/payer_transitions.csv'
INTO TABLE stg_payer_transitions
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@PATIENT,@START_YEAR,@END_YEAR,@PAYER,@OWNERSHIP)
SET
  PATIENT    = NULLIF(@PATIENT,''),
  START_YEAR = NULLIF(@START_YEAR,''),
  END_YEAR   = NULLIF(@END_YEAR,''),
  PAYER      = NULLIF(@PAYER,''),
  OWNERSHIP  = NULLIF(@OWNERSHIP,'');

# Step 2) Filter Data
-- 2 year window
SET @win_start := '2017-01-01';
SET @win_end   := '2019-01-01';

-- Encounters within the selected window
DROP TEMPORARY TABLE IF EXISTS hospital_staging.enc_win;
CREATE TEMPORARY TABLE hospital_staging.enc_win AS
SELECT *
FROM hospital_staging.stg_encounters
WHERE `START` >= @win_start AND `START` < @win_end;

-- Candidate patients from the window
DROP TEMPORARY TABLE IF EXISTS hospital_staging.pat_pool;
CREATE TEMPORARY TABLE hospital_staging.pat_pool AS
SELECT DISTINCT PATIENT AS patient_source_id
FROM enc_win;

-- Keep up to 1000 patients
DROP TEMPORARY TABLE IF EXISTS hospital_staging.pat_keep;
CREATE TEMPORARY TABLE hospital_staging.pat_keep AS
SELECT patient_source_id
FROM pat_pool
ORDER BY RAND(7)
LIMIT 1000;

ALTER TABLE pat_keep ADD PRIMARY KEY (patient_source_id);

-- Keep only windowed encounters for kept patients
DROP TEMPORARY TABLE IF EXISTS hospital_staging.enc_keep;
CREATE TEMPORARY TABLE hospital_staging.enc_keep AS
SELECT e.*
FROM enc_win e
JOIN pat_keep k ON k.patient_source_id = e.PATIENT;

ALTER TABLE enc_keep
  ADD INDEX ix_enc_keep_patient (PATIENT),
  ADD INDEX ix_enc_keep_encounter (Id);
